### ISSUE TITLE
FAQ rendered incorrectly

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#60]
I noticed a (minor) error in the rendering/formatting of one of the FAQs. See attached, item 10 is indented inconsistently. Looking at the rst file, I cannot see anything wrong with it.

![Screen Shot 2019-07-05 at 09 48 11](https://user-images.githubusercontent.com/899043/60706631-2cb41700-9f0a-11e9-9501-837e8b65c0d8.png)

**Comment by robertoostenveld** [comment]
oh, under item 8 of the same FAQ there is another one.

**Comment by hurngchunlee** [comment]
I fixed them.  In the ReStructuredText, the indent is not about a fix amount of space characters or TABs, it is more about alignment.  The issue is due to the fact that the item body is not aligned with the item title.

Given this reason, I would always use `#.` for [auto enumeration](http://docutils.sourceforge.net/docs/user/rst/quickref.html#enumerated-lists) instead of manually using `1., 2., ..., 10,`.
