### ISSUE TITLE
help on manifest checking needs to be updated

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-configurable-content-donders#66]
The documentation specifies https://data.donders.ru.nl/doc/help/user-manual/transfer-data/check-transferred-data.html but in reality the large collections do not allow the download of the manifest any more. 

This must be updated, i.e. explain that the manifest is included as a file in the collection.

**Comment by hurngchunlee** [comment]
@jesask I suppose this is something for the data stewards to update?

**Comment by jesask** [comment]
@hurngchunlee I agree and will add this to the "documentation updates" to-do; i.e. that the system administrator should be contacted for the manifest file for large datasets and that MANIFEST, README and LICENSE file will be added to the collection.

I missed the details though..; when are the LICENSE, MANIFEST and README file added to the collection? I assume only after publication? This concerns only DSCs, right?

**Comment by hurngchunlee** [comment]
@jesask It actually concerns:

- archived DAC/RDC
- published DSC

However, the README and LICENSE files are only generated for published DSC along with the MANIFEST file; for archived DAC/RDC, only the MANIFEST file is generated.

The main point of this issue is that the MANIFEST file for archived DAC/RDC and published DSC is available as part of the data.

Let me know if you need more about the details.

**Comment by jesask** [comment]
@hurngchunlee clear, thanks!

**Comment by robertoostenveld** [comment]
ehh, .... I actually think that this issue should not yet be closed, until it has been resolved and the documentation on the website updated. Otherwise the closed issue disappears from the [TODO list](https://github.com/donders-research-data-management/rdm-configurable-content-donders/issues).

Or are you moving it over to another TODO list elsewhere (e.g. one shared with @miriamkos and @benglitz)?
